### ISSUE TITLE
Can't save subsetted ontotrace matrix as nexml

### ISSUE THREAD

**Issue by pmabee** [phenoscape/rphenoscape#61] opened 2019-05-17 16:58 UTC
```R
write.nexml(Ictalurus, file="Ictalurus-only-matrix.xml")
 Error in as(x, "nexml") : 
   no method or default for coercing “tbl_df” to “nexml”
```

**Comment by hlapp** [comment] 2019-06-05 21:02
@pmabee (or @wdahdul) could you provide the complete sequence of commands for reproducing the error. Specifically, I can't see how `Ictalurus` was obtained, and hence what type of object it is.

**Comment by wdahdul** [comment] 2019-06-05 23:09
```
nex <- pk_get_ontotrace_xml(taxon = "Ictaluridae", entity = 'fin spine')
m <- pk_get_ontotrace(nex) #gets matrix as a data.frame from nexml object
is_desc <- pk_is_descendant('Ictalurus', m$taxa)
mIctalurus <- m[is_desc, ]
write.nexml(mIctalurus, file="Ictalurus-matrix.xml")

```

> Error in as(x, "nexml") : 
>   no method or default for coercing “tbl_df” to “nexml”

**Comment by hlapp** [comment] 2019-06-06 17:19
Please see the manual page of RNeXML::write.nexml. The correct invocation is the following:
```R
write.nexml(characters = my.matrix, file="my.file.xml")
```

This does currently fail too, though, due to a bug in RNeXML.

**Comment by hlapp** [comment] 2019-06-10 20:20
The originally observed bug in RNeXML is now fixed, but that only led to the next one to surface, see rOpenSci/RNeXML#239. 

I'd suggest we take this out of the Evolution Workshop curriculum, as there are barely any analysis or viz programs that read NeXML as input anyway. Better to pass the subset matrix on to some other method that expects a matrix, or write it out using ape.

**Closed** 2019-06-20 18:40 UTC
Labels: documentation, enhancement
