### ISSUE TITLE
Polymorphic characters

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#16] opened 2018-09-18 21:49 UTC
Compared to web UI OntoTrace query, a query with RPhenoscape didn't include polymorphic coding for one taxon (see screenshots attached)

<img width="1072" alt="screen shot 2018-09-18 at 2 31 24 pm" src="https://user-images.githubusercontent.com/957012/45718494-0a573580-bb52-11e8-84f7-a65f71d91a8c.png">
<img width="1082" alt="screen shot 2018-09-18 at 2 31 45 pm" src="https://user-images.githubusercontent.com/957012/45718495-0a573580-bb52-11e8-852a-d3af73b5c89a.png">

**Comment by wdahdul** [comment] 2018-09-18 21:50
nex <- pk_get_ontotrace_xml(taxon = c("Ictalurus"), entity = "fin spine")

**Comment by hlapp** [comment] 2018-09-19 21:41
@wdahdul I assume you must have written out the NeXML file from R somehow? Can you please specify how?

I'll assume that the polymorphic encoding is transmitted correctly in the NeXML file that Rphenoscape obtains from the API, and that therefore what you're showing is probably not the retrieved NeXML file. So I would suspect that it's the method in R that's writing a NeXML file, which is a [RNeXML](https://github.com/ropensci/RNeXML) capability, not one in Rphenoscape.

**Comment by wdahdul** [comment] 2018-09-19 23:53
I used this: 
> write.nexml(nex, file="test2.xml")

**Comment by hlapp** [comment] 2018-09-28 17:10
It may be worth noting that extracting the character matrix from this OntoTrace object fails in the same place and with the same error as in #19.

@wdahdul would you mind reposting this issue on the [RNeXML tracker](https://github.com/ropensci/RNeXML/issues)? (I don't think that the issue when writing the NeXML file is connected with ropensci/RNeXML#171 (the root cause behind #19), though it's not impossible.) If you need or want to, you can refer back to this issue as `xu-hong/rphenoscape#16`.

**Comment by hlapp** [comment] 2018-10-27 01:08
I reported this on the RNeXML tracker as ropensci/RNeXML#191, which was subsequently fixed by @cboettig in ropensci/RNeXML#192.

**Closed by hlapp** 2018-10-27 01:08 UTC

**Comment by hlapp** [comment] 2018-11-03 00:38
New version of RNeXML is on CRAN now. Upgrading rphenoscape should result in RNeXML being upgraded. See README.
