### ISSUE TITLE
dependency matrix error

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#108] opened 2019-10-02 22:10 UTC
```
> terms <- readLines("fin_terms.txt") 
> terms_trim <- trimws(terms) 
> dep1 <- pa_dep_matrix(terms_trim)
Error in get_csv_data(pkb_api("/entity/dependency"), query = queryseq,  : 
  (500) Internal Server Error: Malformed parameters.
```

same error when query with list of IRIs
```
> terms_iris <- lapply(terms_trim, pk_get_iri, as = "uberon")
> dep2 <- pa_dep_matrix(terms_iris)
Error in get_csv_data(pkb_api("/entity/dependency"), query = queryseq,  : 
  (500) Internal Server Error: Malformed parameters.
[fin_terms.txt](https://github.com/phenoscape/rphenoscape/files/3683589/fin_terms.txt)

```

**Comment by hlapp** [comment] 2019-10-04 14:59
@wdahdul do you have the `fin_terms.txt` file somewhere where I can access it? I can't reproduce the error with the `catfish_anat.txt` file you attached to #109.

I suspect that might be going on is that a term label fails to get resolved to an IRI. However, if that happens you should see a warning about it, so if indeed that's the case I'm wondering why that doesn't get printed. Also, if this is indeed the culprit, perhaps it would be worth to change the behavior that even a single term failing to resolve is an unrecoverable error.

**Comment by wdahdul** [comment] 2019-10-04 16:38
Here's the file with fin terms:
[fin_terms.txt](https://github.com/phenoscape/rphenoscape/files/3691474/fin_terms.txt)

**Comment by hlapp** [comment] 2019-10-07 00:43
Thanks @wdahdul. This is due to a failure and bug in the KB API, which I reported here: phenoscape/phenoscape-kb-services#171

**Comment by hlapp** [comment] 2019-10-28 16:13
Fixed in KB API, and confirmed to be working now.

**Closed by hlapp** 2019-10-28 16:13 UTC
Labels: cannot fix here
